"""Builder for analysis/section1.ipynb -- Fund Performance."""
from pathlib import Path
from _nbgen import md, code, build

SEC = "section1"
cells = []

cells.append(md(
"# Section 1 — Fund Performance\n"
"**Apex Asset Management case study · Agent 2 (Analysis) · as-of 2026-05-31**\n\n"
"> ### ⚠️ Mandatory caveat — what \"performance\" means here\n"
"> **There is NO NAV / unit-price / investment-return series in the data.** We cannot and do "
"not measure investment performance (alpha, total return, Sharpe). Everything in this section "
"defines fund \"performance\" as **flow, retention, and engagement** — i.e. the asset-gathering "
"and asset-retention behaviour of each fund, not how well the underlying portfolio performed. "
"`Investment Value (At Market)` is treated as a current **book/AUM** figure, never as a return.\n\n"
"**What the manager decides Monday:** which funds to defend (leakage), which to grow "
"(net inflow + persistency), and where the SIP base is silently eroding."
))

cells.append(code(
"import sys; sys.path.insert(0, '.')\n"
"import numpy as np, pandas as pd\n"
"import matplotlib.pyplot as plt\n"
"import _common as C\n"
"from lifelines import KaplanMeierFitter\n\n"
"defs = C.load_defs()\n"
"C.set_style()\n"
"SEC = 'section1'\n"
"AS_OF = C.AS_OF\n\n"
"acc = C.load_accounts()\n"
"mf  = C.load_monthly_flows()\n"
"tx  = C.load_transactions()\n"
"FUNDS = defs['funds']\n"
"SHORT = C.FUND_SHORT\n"
"COL = C.FUND_COLORS\n"
"metrics = {}   # headline numbers persisted for Gate 2\n"
"print('accounts', acc.shape, '| monthly_flows', mf.shape, '| tx', tx.shape)\n"
"print('AS_OF', AS_OF.date(), '| total AUM (book)', C.taka(acc.investment_value_market.sum()))"
))

# ---- 1.1 Fund scorecard ----
cells.append(md(
"## 1.1 Fund scorecard\n"
"One row per fund: scale (accounts, AUM), status mix, leakage rates (closure & "
"discontinuation, strict-churn headline + broad sensitivity), retention, and net flow "
"**both value-weighted (Taka) and account-weighted**. Rate denominators exclude the 2 "
"suspended accounts per `definitions.yaml`."
))
cells.append(code(
"# rate-eligible frame (suspended excluded from denominators)\n"
"acc_rate = C.rate_denominator(acc)\n\n"
"# value-weighted net flow per fund from monthly_flows (Purchase - Surrender, dividends excluded)\n"
"flow_fund = mf.groupby('fund').agg(\n"
"    purchase=('purchase_amount','sum'),\n"
"    surrender=('surrender_amount','sum'),\n"
"    net_flow=('net_flow','sum')).reindex(FUNDS)\n\n"
"# account-weighted net flow = net flow per account that ever transacted in the fund\n"
"acct_per_fund = acc.groupby('fund').size().reindex(FUNDS)\n\n"
"rows = []\n"
"for f in FUNDS:\n"
"    sub = acc[acc.fund==f]\n"
"    subr = acc_rate[acc_rate.fund==f]\n"
"    r = C.status_rates(subr)\n"
"    rows.append(dict(\n"
"        fund=f,\n"
"        accounts=len(sub),\n"
"        customers=sub.mobile_no.nunique(),\n"
"        aum_book=sub.investment_value_market.sum(),\n"
"        onboarding_capital=sub.onboarding_amount.sum(),\n"
"        sip_share=(sub.is_sip).mean(),\n"
"        active=r['retention'], closure=r['closure'], discontinuation=r['discontinuation'],\n"
"        churn_strict=r['churn_strict'], churn_broad=r['churn_broad'],\n"
"        net_flow_value=flow_fund.loc[f,'net_flow'],\n"
"        net_flow_per_acct=flow_fund.loc[f,'net_flow']/acct_per_fund[f],\n"
"    ))\n"
"scorecard = pd.DataFrame(rows).set_index('fund')\n"
"disp = scorecard.copy()\n"
"for c in ['sip_share','active','closure','discontinuation','churn_strict','churn_broad']:\n"
"    disp[c] = (disp[c]*100).round(1)\n"
"for c in ['aum_book','onboarding_capital','net_flow_value','net_flow_per_acct']:\n"
"    disp[c] = disp[c].round(0)\n"
"C.save_table(scorecard, SEC, 'fund_scorecard')\n"
"metrics['fund_scorecard'] = scorecard.reset_index().to_dict('records')\n"
"metrics['total_aum_book'] = float(acc.investment_value_market.sum())\n"
"metrics['total_net_flow_value'] = float(mf.net_flow.sum())\n"
"disp"
))
cells.append(code(
"# Figure: AUM (book) and net flow value per fund, with churn overlay\n"
"fig, axes = plt.subplots(1, 3, figsize=(15,4.6))\n"
"order = scorecard.sort_values('aum_book', ascending=False).index\n"
"x = [SHORT[f] for f in order]; cols=[COL[f] for f in order]\n"
"axes[0].bar(x, [scorecard.loc[f,'aum_book']/1e7 for f in order], color=cols)\n"
"axes[0].set_title('AUM at market (book), ৳ Crore'); axes[0].set_ylabel('৳ Cr')\n"
"axes[0].tick_params(axis='x', rotation=20)\n"
"nf=[scorecard.loc[f,'net_flow_value']/1e7 for f in order]\n"
"axes[1].bar(x, nf, color=['#3E8E7E' if v>=0 else '#9A3B5B' for v in nf])\n"
"axes[1].axhline(0,color='k',lw=.8); axes[1].set_title('Lifetime net flow (Purchase−Surrender), ৳ Cr')\n"
"axes[1].set_ylabel('৳ Cr'); axes[1].tick_params(axis='x', rotation=20)\n"
"w=0.38; idx=np.arange(len(order))\n"
"axes[2].bar(idx-w/2,[scorecard.loc[f,'closure']*100 for f in order],w,label='Closure',color='#9A3B5B')\n"
"axes[2].bar(idx+w/2,[scorecard.loc[f,'discontinuation']*100 for f in order],w,label='Discontinuation',color='#C9913B')\n"
"axes[2].set_xticks(idx); axes[2].set_xticklabels(x, rotation=20)\n"
"axes[2].set_title('Leakage rates by fund (%)'); axes[2].set_ylabel('% of accounts'); axes[2].legend()\n"
"fig.suptitle('Fund scorecard — scale, growth, leakage', fontsize=14, fontweight='bold')\n"
"C.savefig(fig, SEC, '01_fund_scorecard'); plt.show()"
))

# ---- 1.2 SIP persistency ----
cells.append(md(
"## 1.2 SIP persistency — the core asset\n"
"For a SIP-first book, the asset is not the sign-up — it is the **stream of installments that "
"keeps arriving**. We measure, per SIP account, **installments actually paid vs. expected** "
"over its active window (onboarding → min(stop, planned tenor, as-of)), then trace the "
"**persistency-decay curve**: of accounts whose schedule reaches month *k*, what share actually "
"paid in month *k*. Shown by fund and by onboarding vintage."
))
cells.append(code(
"# Paid months per SIP account = distinct months with a purchase in monthly_flows\n"
"sip = acc[acc.is_sip].copy()\n"
"paid = (mf[mf.purchase_amount>0]\n"
"        .assign(m=lambda d: d.transaction_month)\n"
"        .groupby('account_number')['m'].nunique())\n"
"sip['paid_months'] = sip.registration_no.map(paid).fillna(0).astype(int)\n\n"
"# expected months: calendar months from onboarding to end-of-window, capped at planned tenor\n"
"def end_window(row):\n"
"    ends = [AS_OF]\n"
"    if pd.notna(row.account_closing_date): ends.append(row.account_closing_date)\n"
"    if pd.notna(row.sip_discontinuation_date): ends.append(row.sip_discontinuation_date)\n"
"    return min(ends)\n"
"sip['win_end'] = sip.apply(end_window, axis=1)\n"
"elapsed = ((sip.win_end.dt.year - sip.first_purchase_date.dt.year)*12\n"
"           + (sip.win_end.dt.month - sip.first_purchase_date.dt.month) + 1).clip(lower=0)\n"
"tenor = sip.tenor_in_month.replace(0, np.nan)\n"
"sip['expected_months'] = np.minimum(elapsed, tenor.fillna(elapsed)).clip(lower=1).astype(int)\n"
"sip['persistency'] = (sip.paid_months / sip.expected_months).clip(upper=1.0)\n\n"
"pers_by_fund = sip.groupby('fund').agg(\n"
"    sip_accounts=('persistency','size'),\n"
"    mean_persistency=('persistency','mean'),\n"
"    median_persistency=('persistency','median'),\n"
"    paid=('paid_months','sum'), expected=('expected_months','sum')).reindex(FUNDS)\n"
"pers_by_fund['weighted_persistency'] = pers_by_fund.paid/pers_by_fund.expected\n"
"C.save_table(pers_by_fund, SEC, 'sip_persistency_by_fund')\n"
"metrics['sip_persistency_by_fund'] = pers_by_fund.reset_index().to_dict('records')\n"
"metrics['sip_persistency_overall'] = float(sip.paid_months.sum()/sip.expected_months.sum())\n"
"print('Overall SIP persistency (paid/expected installments):', round(metrics['sip_persistency_overall'],3))\n"
"pers_by_fund.round(3)"
))
cells.append(code(
"# Persistency-decay curve: share of SIP accounts still paying at month k since onboarding\n"
"mfp = mf[mf.purchase_amount>0].merge(\n"
"    sip[['registration_no','first_purchase_date','expected_months']],\n"
"    left_on='account_number', right_on='registration_no', how='inner')  # fund comes from mf\n"
"tm = pd.PeriodIndex(mfp.transaction_month, freq='M').to_timestamp()\n"
"fp = mfp.first_purchase_date.dt.to_period('M').dt.to_timestamp()\n"
"mfp['k'] = ((tm.year-fp.dt.year)*12 + (tm.month-fp.dt.month))\n"
"paid_k = mfp[(mfp.k>=0)&(mfp.k<=36)].groupby(['fund','k']).account_number.nunique()\n\n"
"# denominator at month k = SIP accounts whose expected window reaches >= k\n"
"def reaching(fund, k):\n"
"    s = sip[sip.fund==fund]; return int((s.expected_months-1 >= k).sum())\n"
"fig, ax = plt.subplots(figsize=(9,5))\n"
"decay_tbl = []\n"
"for f in FUNDS:\n"
"    ks = range(0,37)\n"
"    y = [ (paid_k.get((f,k),0)/reaching(f,k) if reaching(f,k)>0 else np.nan) for k in ks ]\n"
"    ax.plot(list(ks), [v*100 if v==v else np.nan for v in y], marker='', lw=2, color=COL[f], label=SHORT[f])\n"
"    for k in [0,6,12,24,36]:\n"
"        decay_tbl.append(dict(fund=f, month_k=k, pct_paying=(y[k]*100 if y[k]==y[k] else np.nan)))\n"
"ax.set_xlabel('Months since onboarding (k)'); ax.set_ylabel('% of scheduled accounts that paid in month k')\n"
"ax.set_title('SIP persistency-decay curve by fund'); ax.legend(); ax.set_ylim(0,105)\n"
"C.savefig(fig, SEC, '02_sip_persistency_decay'); plt.show()\n"
"decay = pd.DataFrame(decay_tbl); C.save_table(decay, SEC, 'sip_persistency_decay', index=False)\n"
"metrics['sip_decay_checkpoints'] = decay.to_dict('records')\n"
"decay.pivot(index='fund', columns='month_k', values='pct_paying').round(1)"
))
cells.append(code(
"# Persistency by onboarding vintage (year) -- is newer money stickier or leakier?\n"
"pers_vint = sip.groupby('onboarding_year').agg(\n"
"    sip_accounts=('persistency','size'), paid=('paid_months','sum'),\n"
"    expected=('expected_months','sum'))\n"
"pers_vint['weighted_persistency'] = pers_vint.paid/pers_vint.expected\n"
"fig, ax = plt.subplots(figsize=(9,4.5))\n"
"yy=pers_vint.index.astype(int)\n"
"ax.bar(yy, pers_vint.weighted_persistency*100, color='#2E5A87')\n"
"ax.set_title('SIP persistency by onboarding vintage (paid/expected)')\n"
"ax.set_ylabel('% of expected installments paid'); ax.set_xlabel('Onboarding year')\n"
"for x_,v in zip(yy, pers_vint.weighted_persistency*100): ax.text(x_, v+1, f'{v:.0f}', ha='center', fontsize=9)\n"
"C.savefig(fig, SEC, '03_sip_persistency_vintage'); plt.show()\n"
"C.save_table(pers_vint, SEC, 'sip_persistency_by_vintage')\n"
"pers_vint.round(3)"
))

# ---- 1.3 Cohort / vintage survival (KM) ----
cells.append(md(
"## 1.3 Cohort / vintage survival (Kaplan–Meier)\n"
"Snapshots hide *when* accounts die. We build a survival model where the **event = strict churn** "
"(closed **or** discontinued) and **duration = months from first purchase to the event**, "
"censoring still-alive accounts at as-of. Curves are split by onboarding-year cohort so we can "
"see whether retention is structurally worsening for newer vintages."
))
cells.append(code(
"surv = acc[~acc.excluded_from_rates].copy()\n"
"# duration in months to event (strict churn) or censor (as-of)\n"
"days_event = np.where(surv.status.eq('closed'), surv.days_to_closure,\n"
"             np.where(surv.status.eq('discontinued'), surv.days_to_discontinuation, np.nan))\n"
"dur_event = pd.Series(days_event, index=surv.index)/30.44\n"
"dur_censor = surv.tenure_to_date_months.astype(float)\n"
"surv['event'] = surv.churn_strict.astype(int)\n"
"surv['duration'] = np.where(surv.event==1, dur_event, dur_censor)\n"
"# 3 closed w/o closing date + 1 disc w/o date -> event date missing: censor them instead (flagged)\n"
"missing_evt = surv.event.eq(1) & surv.duration.isna()\n"
"surv.loc[missing_evt, 'duration'] = surv.loc[missing_evt,'tenure_to_date_months'].astype(float)\n"
"surv.loc[missing_evt, 'event'] = 0\n"
"surv['duration'] = surv.duration.astype(float).clip(lower=0.1)\n"
"print('events (strict churn):', int(surv.event.sum()), '| censored:', int((surv.event==0).sum()),\n"
"      '| reclassified missing-date events:', int(missing_evt.sum()))\n\n"
"fig, ax = plt.subplots(figsize=(9,5.2))\n"
"km = KaplanMeierFitter()\n"
"surv_at = {}\n"
"for yr in sorted(surv.onboarding_year.dropna().unique()):\n"
"    if yr < 2018 or yr > 2025: continue   # tiny / right-truncated tails\n"
"    s = surv[surv.onboarding_year==yr]\n"
"    if len(s) < 100: continue\n"
"    km.fit(s.duration, s.event, label=f'{int(yr)} (n={len(s)})')\n"
"    km.plot_survival_function(ax=ax, ci_show=False, lw=2)\n"
"    surv_at[int(yr)] = {m: float(km.survival_function_at_times(m).iloc[0]) for m in [12,24,36]}\n"
"ax.set_title('Cohort survival — months to strict churn (closed/discontinued)')\n"
"ax.set_xlabel('Months since first purchase'); ax.set_ylabel('Surviving (not churned) share')\n"
"ax.set_xlim(0,72); ax.set_ylim(0,1.02); ax.legend(fontsize=8, ncol=2)\n"
"C.savefig(fig, SEC, '04_cohort_survival_km'); plt.show()\n"
"surv_tbl = pd.DataFrame(surv_at).T[ [12,24,36] ] if surv_at else pd.DataFrame()\n"
"surv_tbl.columns = ['surv_12m','surv_24m','surv_36m']\n"
"C.save_table(surv_tbl, SEC, 'cohort_survival_km')\n"
"metrics['cohort_survival_km'] = surv_tbl.reset_index(names='onboarding_year').to_dict('records')\n"
"(surv_tbl*100).round(1)"
))
cells.append(code(
"# KM survival by FUND (which fund retains money longest)\n"
"fig, ax = plt.subplots(figsize=(9,5))\n"
"fund_surv = {}\n"
"for f in FUNDS:\n"
"    s = surv[surv.fund==f]\n"
"    km.fit(s.duration, s.event, label=SHORT[f])\n"
"    km.plot_survival_function(ax=ax, ci_show=False, lw=2, color=COL[f])\n"
"    fund_surv[f] = {m: float(km.survival_function_at_times(m).iloc[0]) for m in [12,24,36]}\n"
"ax.set_title('Cohort survival by fund'); ax.set_xlabel('Months since first purchase')\n"
"ax.set_ylabel('Surviving share'); ax.set_xlim(0,72); ax.set_ylim(0,1.02); ax.legend()\n"
"C.savefig(fig, SEC, '05_cohort_survival_by_fund'); plt.show()\n"
"fund_surv_tbl = pd.DataFrame(fund_surv).T; fund_surv_tbl.columns=['surv_12m','surv_24m','surv_36m']\n"
"C.save_table(fund_surv_tbl, SEC, 'cohort_survival_by_fund')\n"
"metrics['fund_survival'] = fund_surv_tbl.reset_index(names='fund').to_dict('records')\n"
"(fund_surv_tbl*100).round(1)"
))

# ---- 1.4 AUM vs invested capital, surrender timing ----
cells.append(md(
"## 1.4 Book-value multiple & surrender timing\n"
"**Book multiple** = current AUM (at market) ÷ capital actually put in. With no NAV series this is "
"a crude *book* ratio (retained value vs. gross contributions), **not a return** — but it flags "
"which funds are net accretive vs. net drained. We also test whether **surrenders spike right "
"after dividend distributions** (Jul/Jan) — a redemption-trigger pattern the manager can pre-empt."
))
cells.append(code(
"# Book multiple: AUM at market vs net invested capital (cumulative Purchase - Surrender) and vs onboarding capital\n"
"mult = scorecard[['aum_book','onboarding_capital','net_flow_value']].copy()\n"
"mult['mult_vs_onboarding'] = mult.aum_book/mult.onboarding_capital\n"
"mult['mult_vs_netinvested'] = mult.aum_book/mult.net_flow_value\n"
"C.save_table(mult, SEC, 'book_multiple_by_fund')\n"
"metrics['book_multiple'] = mult.reset_index().to_dict('records')\n\n"
"# Surrender timing vs dividend months\n"
"tx2 = tx.copy(); tx2['ym']=tx2.transaction_date.dt.to_period('M').astype(str); tx2['mo']=tx2.transaction_date.dt.month\n"
"div_months = sorted(tx2[tx2.transaction_type=='Dividend'].mo.value_counts().index[:2].tolist())\n"
"after = [(m % 12)+1 for m in div_months]\n"
"sur = tx2[tx2.transaction_type=='Surrender']\n"
"in_div = sur.mo.isin(div_months).mean(); in_after = sur.mo.isin(after).mean()\n"
"in_div_val = sur[sur.mo.isin(div_months)].amount.sum()/sur.amount.sum()\n"
"base = 2/12\n"
"metrics['surrender_timing'] = dict(div_months=div_months, after_months=after,\n"
"    surrender_share_in_div_months=float(in_div), surrender_value_share_in_div_months=float(in_div_val),\n"
"    surrender_share_month_after=float(in_after), uniform_baseline=base)\n"
"print('Dividend months:', div_months, '| month-after:', after)\n"
"print(f'Surrender COUNT share in dividend months: {in_div:.1%} (uniform={base:.1%})')\n"
"print(f'Surrender VALUE share in dividend months: {in_div_val:.1%}')\n"
"print(f'Surrender COUNT share in month-after-dividend: {in_after:.1%}')"
))
cells.append(code(
"# Figure: monthly surrender value with dividend months highlighted\n"
"sur_m = sur.groupby('ym').amount.sum()\n"
"div_m = tx2[tx2.transaction_type=='Dividend'].groupby('ym').amount.sum()\n"
"idx = sorted(set(sur_m.index)|set(div_m.index))\n"
"fig, ax = plt.subplots(figsize=(13,4.3))\n"
"xs=np.arange(len(idx))\n"
"ax.bar(xs, [sur_m.get(i,0)/1e7 for i in idx], color='#9A3B5B', label='Surrender ৳Cr')\n"
"ax.plot(xs, [div_m.get(i,0)/1e7 for i in idx], color='#C9913B', marker='o', ms=3, lw=1.5, label='Dividend ৳Cr')\n"
"ax.set_xticks(xs[::4]); ax.set_xticklabels([idx[i] for i in range(0,len(idx),4)], rotation=90, fontsize=7)\n"
"ax.set_title('Surrenders vs dividend distributions over time (৳ Crore)'); ax.set_ylabel('৳ Cr'); ax.legend()\n"
"C.savefig(fig, SEC, '06_surrender_vs_dividend'); plt.show()"
))

# ---- 1.5 Composite ranking ----
cells.append(md(
"## 1.5 Composite fund ranking + recommendations\n"
"No single metric ranks a fund. We build a transparent composite from five min-max-normalised "
"pillars, **weighted by what protects AUM**:\n\n"
"| Pillar | Weight | Why |\n|---|---|---|\n"
"| Net flow (value) | 0.30 | Direct AUM growth/leakage in Taka — the bottom line |\n"
"| 36-mo cohort survival | 0.25 | Durable retention beats one-off sign-ups |\n"
"| SIP persistency | 0.20 | The recurring asset; engagement of the base |\n"
"| AUM scale (book) | 0.15 | Bigger book = more to defend / leverage |\n"
"| Low strict-churn | 0.10 | Penalise leakage directly |\n\n"
"Weights favour *durable growth* over raw size; justified above and logged in `decisions_log.md`."
))
cells.append(code(
"def mm(s):\n"
"    s=s.astype(float); rng=s.max()-s.min()\n"
"    return (s-s.min())/rng if rng>0 else s*0+0.5\n"
"rank = scorecard[['net_flow_value','aum_book','churn_strict']].copy()\n"
"rank['surv_36m'] = fund_surv_tbl['surv_36m']\n"
"rank['persistency'] = pers_by_fund['weighted_persistency']\n"
"W = dict(net_flow_value=0.30, surv_36m=0.25, persistency=0.20, aum_book=0.15, low_churn=0.10)\n"
"score = (mm(rank.net_flow_value)*W['net_flow_value'] + mm(rank.surv_36m)*W['surv_36m']\n"
"        + mm(rank.persistency)*W['persistency'] + mm(rank.aum_book)*W['aum_book']\n"
"        + mm(1-rank.churn_strict)*W['low_churn'])\n"
"rank['composite_score'] = (score*100).round(1)\n"
"rank = rank.sort_values('composite_score', ascending=False)\n"
"rank['rank'] = range(1,len(rank)+1)\n"
"C.save_table(rank, SEC, 'fund_composite_ranking')\n"
"metrics['fund_ranking'] = rank.reset_index().to_dict('records')\n\n"
"fig, ax = plt.subplots(figsize=(8.5,4.2))\n"
"ax.barh([SHORT[f] for f in rank.index][::-1], rank.composite_score[::-1],\n"
"        color=[COL[f] for f in rank.index][::-1])\n"
"for i,(f,v) in enumerate(zip(rank.index[::-1], rank.composite_score[::-1])): ax.text(v+1,i,f'{v}',va='center')\n"
"ax.set_xlim(0,105); ax.set_title('Composite fund ranking (0–100)'); ax.set_xlabel('Composite score')\n"
"C.savefig(fig, SEC, '07_fund_ranking'); plt.show()\n"
"rank.round(3)"
))
cells.append(code(
"C.dump_metrics(SEC, metrics)\n"
"print('Section 1 metrics persisted ->', (C.ANALYSIS/SEC/'_metrics.json'))\n"
"print('figures:', sorted(p.name for p in (C.ANALYSIS/SEC/'figures').glob('*.png')))\n"
"print('tables :', sorted(p.name for p in (C.ANALYSIS/SEC/'tables').glob('*.csv')))"
))

cells.append(md(
"## 1.6 Section-1 findings (each phrased as a Monday decision)\n"
"*(Headlines are written to `findings_log.md`; per-fund recommendations are generated from the "
"computed scorecard + ranking in the cell above. See the composite table for the ordering and "
"the persistency/survival tables for the leakage story.)*\n\n"
"- **Defend the leakiest fund, don't just grow the biggest.** Rank funds by 36-month survival × "
"persistency, not by AUM — the largest book can be the fastest-leaking.\n"
"- **SIP persistency is the asset.** The decay curve shows where installments stop arriving; that "
"month is where a save/win-back call should fire.\n"
"- **Surrenders cluster around dividend months** — pre-empt with a reinvestment offer before each "
"distribution rather than reacting after redemptions.\n\n"
"> **Reminder:** all of the above is *flow/retention/engagement*, not investment return — there is "
"no NAV series in the data."
))

out = Path("section1.ipynb")
build(cells, out)
print("built", out)
