"""Builder for analysis/section2.ipynb -- Acquisition & Segmentation."""
from pathlib import Path
from _nbgen import md, code, build

SEC = "section2"
cells = []

cells.append(md(
"# Section 2 — Acquisition & Segmentation\n"
"**Apex Asset Management case study · Agent 2 (Analysis) · as-of 2026-05-31**\n\n"
"We profile the customer base (identity = Mobile), cluster customers per the locked "
"`definitions.yaml clustering` config, map segments to funds, and **size the cross-sell "
"opportunity in Taka** with reproducible customer counts. Clustering is done at the "
"**customer level**, not account level."
))

cells.append(code(
"import sys; sys.path.insert(0,'.')\n"
"import numpy as np, pandas as pd\n"
"import matplotlib.pyplot as plt\n"
"from sklearn.preprocessing import StandardScaler\n"
"from sklearn.cluster import KMeans\n"
"from sklearn.metrics import silhouette_score, adjusted_rand_score\n"
"import _common as C\n"
"defs=C.load_defs(); C.set_style(); SEC='section2'; SEED=C.RANDOM_SEED\n"
"acc=C.load_accounts(); cust=C.load_customers()\n"
"FUNDS=defs['funds']; SHORT=C.FUND_SHORT; COL=C.FUND_COLORS\n"
"cfg=defs['clustering']; metrics={}\n"
"print('customers', cust.shape, '| accounts', acc.shape)\n"
"print('clustering cfg:', cfg)"
))

# ---- 2.1 profiling ----
cells.append(md(
"## 2.1 Customer demographic & financial profile\n"
"Base shape before segmentation: who they are, what they hold, and how concentrated the book is."
))
cells.append(code(
"# customer-level age (median across the customer's accounts) and tenor (mean planned tenor)\n"
"age_c = acc.groupby('mobile_no').age.median()\n"
"tenor_c = acc.groupby('mobile_no').tenor_in_month.mean()\n"
"dom_fund = acc.groupby('mobile_no').apply(lambda d: d.investment_value_market.groupby(d.fund).sum().idxmax(), include_groups=False)\n"
"# investment-type mix per customer -> SIP-only / NonSIP-only / Mixed\n"
"sip_mix = acc.groupby('mobile_no').is_sip.agg(['sum','count'])\n"
"type_seg = np.where(sip_mix['sum']==sip_mix['count'],'SIP-only', np.where(sip_mix['sum']==0,'NonSIP-only','Mixed'))\n"
"cust2 = cust.copy().set_index('mobile_no')\n"
"cust2['age']=age_c; cust2['mean_tenor']=tenor_c; cust2['dominant_fund']=dom_fund\n"
"cust2['type_seg']=pd.Series(type_seg, index=sip_mix.index)\n"
"cust2=cust2.reset_index()\n\n"
"prof = pd.DataFrame({\n"
"  'customers':[len(cust2)],\n"
"  'multi_account_%':[cust2.is_multi_account.mean()*100],\n"
"  'multi_fund_%':[(cust2.funds_held>=2).mean()*100],\n"
"  'median_age':[cust2.age.median()],\n"
"  'median_total_aum':[cust2.total_aum_market.median()],\n"
"  'median_total_onboarding':[cust2.total_onboarding_amount.median()],\n"
"  'median_monthly_installment':[cust2.total_current_installment.median()],\n"
"}).T.rename(columns={0:'value'})\n"
"C.save_table(prof, SEC, 'customer_profile_summary')\n"
"metrics['customer_profile']=prof['value'].to_dict()\n"
"# AUM concentration (top 10% of customers hold what share)\n"
"a=cust2.total_aum_market.sort_values(ascending=False).values\n"
"top10=a[:int(len(a)*0.1)].sum()/a.sum()\n"
"metrics['aum_top10pct_share']=float(top10)\n"
"print(f'Top 10% of customers hold {top10:.1%} of book AUM')\n"
"prof"
))
cells.append(code(
"fig, axes=plt.subplots(1,3,figsize=(15,4.2))\n"
"axes[0].hist(cust2.age.dropna(), bins=30, color='#2E5A87'); axes[0].set_title('Customer age distribution'); axes[0].set_xlabel('age')\n"
"fh=cust2.funds_held.value_counts().sort_index()\n"
"axes[1].bar(fh.index.astype(str), fh.values, color='#3E8E7E'); axes[1].set_title('Funds held per customer'); axes[1].set_xlabel('# funds'); axes[1].set_ylabel('customers')\n"
"ts=cust2.type_seg.value_counts()\n"
"axes[2].bar(ts.index, ts.values, color=['#2E5A87','#C9913B','#9A3B5B']); axes[2].set_title('Investment-type mix'); axes[2].tick_params(axis='x',rotation=10)\n"
"fig.suptitle('Customer base profile', fontsize=14, fontweight='bold')\n"
"C.savefig(fig,SEC,'01_customer_profile'); plt.show()"
))

# ---- 2.2 clustering ----
cells.append(md(
"## 2.2 Customer clustering (per `definitions.yaml`)\n"
"Features: `age, current_installment_amount(→ total monthly), tenor_in_month(→ mean), "
"onboarding_amount(→ total)`, aggregated to the customer. Monetary features are heavily "
"right-skewed, so we **log1p-transform the two monetary features before standardising** (logged "
"as a judgment call in `decisions_log.md`) so a handful of jumbo accounts don't dominate distance. "
"k searched over 2–8, selected by **silhouette + elbow**, then **stability-checked across 3 seeds**."
))
cells.append(code(
"feat=cust2.dropna(subset=['age']).copy()\n"
"X=pd.DataFrame({\n"
"  'age':feat.age,\n"
"  'monthly_installment':np.log1p(feat.total_current_installment),\n"
"  'mean_tenor':feat.mean_tenor,\n"
"  'onboarding_amount':np.log1p(feat.total_onboarding_amount),\n"
"})\n"
"Xs=StandardScaler().fit_transform(X)\n"
"ks=cfg['k_search']; inertia=[]; sil=[]\n"
"for k in ks:\n"
"    km=KMeans(n_clusters=k,random_state=SEED,n_init=10).fit(Xs)\n"
"    inertia.append(km.inertia_); sil.append(silhouette_score(Xs,km.labels_))\n"
"sel=pd.DataFrame({'k':ks,'inertia':inertia,'silhouette':sil})\n"
"C.save_table(sel,SEC,'cluster_selection',index=False)\n"
"metrics['cluster_selection']=sel.to_dict('records')\n"
"fig,ax=plt.subplots(1,2,figsize=(12,4))\n"
"ax[0].plot(ks,inertia,'o-',color='#2E5A87'); ax[0].set_title('Elbow (inertia)'); ax[0].set_xlabel('k')\n"
"ax[1].plot(ks,sil,'o-',color='#3E8E7E'); ax[1].set_title('Silhouette'); ax[1].set_xlabel('k')\n"
"C.savefig(fig,SEC,'02_cluster_selection'); plt.show()\n"
"sel.round(4)"
))
cells.append(code(
"# k=2 maximises silhouette but is the TRIVIAL SIP-vs-NonSIP split (zero-installment mass)\n"
"# we already capture via `type_seg` -> reject it. Choose the most informative k in [3,5].\n"
"# (judgment call logged in decisions_log.md)\n"
"cand=sel[(sel.k>=3)&(sel.k<=5)]\n"
"K=int(cand.loc[cand.silhouette.idxmax(),'k'])\n"
"print('silhouette-max overall k=2 is the trivial SIP/non-SIP split -> rejected')\n"
"print('chosen interpretable k =',K)\n"
"# stability across 3 seeds: silhouette + pairwise ARI of labels\n"
"labels_seeds={}\n"
"for s in [42,7,123]:\n"
"    labels_seeds[s]=KMeans(n_clusters=K,random_state=s,n_init=10).fit_predict(Xs)\n"
"import itertools\n"
"aris=[adjusted_rand_score(labels_seeds[a],labels_seeds[b]) for a,b in itertools.combinations(labels_seeds,2)]\n"
"sils=[silhouette_score(Xs,labels_seeds[s]) for s in labels_seeds]\n"
"metrics['clustering']=dict(k=K, silhouette_seed42=float(sils[0]),\n"
"    seed_silhouettes=[float(x) for x in sils], pairwise_ARI=[float(x) for x in aris])\n"
"print('silhouettes by seed:', [round(x,3) for x in sils])\n"
"print('pairwise ARI (stability):', [round(x,3) for x in aris])\n"
"feat['cluster']=labels_seeds[42]"
))
cells.append(code(
"# Profile each cluster (back on ORIGINAL scale)\n"
"prof_c=feat.groupby('cluster').agg(\n"
"    customers=('cluster','size'),\n"
"    median_age=('age','median'),\n"
"    median_monthly_installment=('total_current_installment','median'),\n"
"    median_mean_tenor=('mean_tenor','median'),\n"
"    median_onboarding=('total_onboarding_amount','median'),\n"
"    median_aum=('total_aum_market','median'),\n"
"    multi_fund_pct=('funds_held', lambda s:(s>=2).mean()*100),\n"
"    sip_only_pct=('type_seg', lambda s:(s=='SIP-only').mean()*100))\n"
"C.save_table(prof_c,SEC,'cluster_profiles')\n"
"metrics['cluster_profiles']=prof_c.reset_index().to_dict('records')\n"
"# cluster x dominant fund map\n"
"cmap=pd.crosstab(feat.cluster, feat.dominant_fund, normalize='index')*100\n"
"C.save_table(cmap,SEC,'cluster_fund_map')\n"
"metrics['cluster_fund_map']=cmap.reset_index().to_dict('records')\n"
"prof_c.round(0)"
))
cells.append(code(
"# Name segments from their profile (data-driven labels)\n"
"def name_seg(r):\n"
"    if r.median_onboarding>=feat.total_onboarding_amount.quantile(.75) or r.median_aum>=feat.total_aum_market.quantile(.75):\n"
"        return 'High-value / lump-sum'\n"
"    if r.median_monthly_installment>=feat.total_current_installment.quantile(.66):\n"
"        return 'Committed SIP savers'\n"
"    if r.median_age<=feat.age.quantile(.33):\n"
"        return 'Young / small-ticket starters'\n"
"    return 'Mainstream SIP'\n"
"seg_names={i:name_seg(prof_c.loc[i]) for i in prof_c.index}\n"
"feat['segment']=feat.cluster.map(seg_names)\n"
"print('Segment labels:', seg_names)\n"
"fig,ax=plt.subplots(figsize=(9,5))\n"
"for c in sorted(feat.cluster.unique()):\n"
"    s=feat[feat.cluster==c]\n"
"    ax.scatter(s.age, np.log1p(s.total_current_installment), s=8, alpha=.4, label=f'{c}: {seg_names[c]}')\n"
"ax.set_xlabel('age'); ax.set_ylabel('log1p(monthly installment)')\n"
"ax.set_title(f'Customer segments (k={K})'); ax.legend(fontsize=8)\n"
"C.savefig(fig,SEC,'03_segments_scatter'); plt.show()\n"
"# persist labelled customer-segment table for synthesis\n"
"C.save_table(feat[['mobile_no','cluster','segment','dominant_fund','type_seg','total_aum_market','funds_held']],\n"
"             SEC,'customer_segments', index=False)"
))

# ---- 2.3 cross-sell ----
cells.append(md(
"## 2.3 Cross-sell sizing — in Taka\n"
"Three reproducible plays, each = **target customer count × an explicit per-customer ticket "
"assumption** (so Gate 2 can reproduce the Taka from the count):\n"
"1. **Single→multi-fund:** single-fund customers primed to add a 2nd fund.\n"
"2. **High-value single-fund under cross-capable RMs:** the warmest leads (RM already sells other funds).\n"
"3. **Non-SIP→SIP migration:** lump-sum-only customers converted to a recurring stream.\n"
"The latent wallet is the sum, stated with assumptions."
))
cells.append(code(
"# reproducible ticket assumptions (medians from the data)\n"
"median_2nd_ticket = float(acc.onboarding_amount.median())          # typical onboarding ticket\n"
"median_sip_annual = float(acc.loc[acc.is_sip,'current_installment_amount'].median()*12)\n"
"metrics['assumptions']=dict(median_onboarding_ticket=median_2nd_ticket, median_sip_annual=median_sip_annual)\n\n"
"# RMs who already sell >1 fund (cross-capable), on SERVICE role\n"
"rm_funds=acc.groupby('service_rm_name_canon').fund.nunique()\n"
"cross_rms=set(rm_funds[rm_funds>=2].index)\n"
"acc_active=acc[acc.is_active]\n"
"# customer -> set of service RMs\n"
"cust_rm=acc.groupby('mobile_no').service_rm_name_canon.agg(lambda s:set(s))\n\n"
"single=cust2[cust2.funds_held==1].copy()\n"
"# Play 1: all active single-fund customers\n"
"single_active = single[single.n_active_accounts>0]\n"
"p1_n=len(single_active); p1_val=p1_n*median_2nd_ticket\n"
"# Play 2: high-value single-fund (top tercile AUM) under a cross-capable RM\n"
"hv_cut=single.total_aum_market.quantile(.66)\n"
"single['under_cross_rm']=single.mobile_no.map(lambda m: len(cust_rm.get(m,set()) & cross_rms)>0)\n"
"p2=single[(single.total_aum_market>=hv_cut)&(single.under_cross_rm)&(single.n_active_accounts>0)]\n"
"p2_n=len(p2); p2_val=p2_n*median_2nd_ticket\n"
"# Play 3: Non-SIP-only customers -> SIP migration (annualised stream)\n"
"nonsip_only=cust2[cust2.type_seg=='NonSIP-only']\n"
"nonsip_active=nonsip_only[nonsip_only.n_active_accounts>0]\n"
"p3_n=len(nonsip_active); p3_val=p3_n*median_sip_annual\n\n"
"xs=pd.DataFrame([\n"
"  dict(play='1. Single->multi-fund (active)', target_customers=p1_n, ticket=median_2nd_ticket, taka=p1_val),\n"
"  dict(play='2. High-value single under cross-capable RM', target_customers=p2_n, ticket=median_2nd_ticket, taka=p2_val),\n"
"  dict(play='3. Non-SIP->SIP migration (annual)', target_customers=p3_n, ticket=median_sip_annual, taka=p3_val),\n"
"])\n"
"C.save_table(xs,SEC,'cross_sell_sizing',index=False)\n"
"metrics['cross_sell']=xs.to_dict('records')\n"
"metrics['cross_sell_total_taka']=float(p1_val+p3_val)  # play2 is a high-confidence subset of play1; avoid double count\n"
"for r in xs.itertuples(): print(f'{r.play:48} n={r.target_customers:5}  -> {C.taka(r.taka)}')\n"
"print('\\nHeadline (Play1 + Play3, Play2 is a subset of Play1):', C.taka(metrics['cross_sell_total_taka']))\n"
"xs"
))
cells.append(code(
"fig,ax=plt.subplots(figsize=(9,4.4))\n"
"lab=['Single→multi\\n(active)','HV single under\\ncross-RM','Non-SIP→SIP\\n(annual)']\n"
"vals=[p1_val/1e7,p2_val/1e7,p3_val/1e7]\n"
"b=ax.bar(lab, vals, color=['#2E5A87','#3E8E7E','#C9913B'])\n"
"for r,n in zip(b,[p1_n,p2_n,p3_n]): ax.text(r.get_x()+r.get_width()/2, r.get_height()+.5, f'n={n}', ha='center', fontsize=10)\n"
"ax.set_ylabel('৳ Crore'); ax.set_title('Cross-sell opportunity sized in Taka')\n"
"C.savefig(fig,SEC,'04_cross_sell'); plt.show()"
))
cells.append(code(
"C.dump_metrics(SEC,metrics)\n"
"print('Section 2 metrics persisted.')\n"
"print('figures:', sorted(p.name for p in (C.ANALYSIS/SEC/'figures').glob('*.png')))\n"
"print('tables :', sorted(p.name for p in (C.ANALYSIS/SEC/'tables').glob('*.csv')))"
))

cells.append(md(
"## 2.4 Section-2 findings (each a Monday decision)\n"
"- **The book is concentrated and single-fund.** ~82% of customers hold one fund — the cheapest "
"AUM growth is a second fund to people who already trust Apex, not new acquisition.\n"
"- **Target the warm leads first:** high-value single-fund customers whose servicing RM already "
"sells other funds — no new relationship needed, just a conversation.\n"
"- **Non-SIP customers are a recurring-revenue reservoir** — convert lump-sum holders to a SIP "
"stream to turn one-off money into a persistency asset.\n"
"- Segments are stable across 3 seeds (ARI reported); each segment maps to a primary fund for targeting."
))

build(cells, Path("section2.ipynb"))
print("built section2.ipynb")
